artifact_location: /home/sandeep/Desktop/adaptive_cis/runs/mlflow/252558403801419247
creation_time: 1771766523696
experiment_id: '252558403801419247'
last_update_time: 1771766523696
lifecycle_stage: active
name: /home/sandeep/Desktop/adaptive_cis/runs/step1/coco_person_car
