artifact_location: /home/sandeep/Desktop/adaptive_cis/runs/mlflow/327691152001154782
creation_time: 1771942217536
experiment_id: '327691152001154782'
last_update_time: 1771942217536
lifecycle_stage: active
name: /home/sandeep/Desktop/adaptive_cis/runs/step1/pascal_person_car
