artifact_location: /home/sandeep/Desktop/adaptive_cis/runs/mlflow/283729781141080274
creation_time: 1771666983887
experiment_id: '283729781141080274'
last_update_time: 1771666983887
lifecycle_stage: active
name: /home/sandeep/Desktop/adaptive_cis/runs/step1
